bot:
  name: "@rocket-cat"
whitelist:
  users:
    - TwizzyDizzy
    - theorenck
  labels:
    - duplicate
    - enhancement
    - "open-for-contributions"
    - "feature-needs-review"
    - "feature-accepted"
    - invalid
    - question
    - wontfix
