bot:
  name: "@rocket-cat"
whitelist:
  users:
    - TwizzyDizzy
    - theorenck
  labels:
    - duplicate
    - enhancement
    - "contributions: welcome"
    - "contributions: only core team"
    - "Feature: Request"
    - "Feature: Planned"
    - "type: bug"
    - invalid
    - question
    - wontfix
