bot:
  name: "@rocket-cat"
whitelist:
  users:
    - TwizzyDizzy
    - theorenck
  labels:
    - duplicate
    - enhancement
    - "contributions welcome"
    - "feature: needs review"
    - "feature: planned"
    - "type: bug"
    - invalid
    - question
    - wontfix
